### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by VSEphpbb** [comment]
@rxu what do you think of this?

**Comment by rxu** [comment]
Looking good in common, but the ```Toggle all``` change can be hard to handle from translation point of view. F.e. in Russian there's no option to express ```mark``` and ```unmark``` actions with 1 word while the literal translation of ```toggle``` will make no sense in this case.

**Comment by VSEphpbb** [comment]
@rxu Fair enough to go back then to the way it was. Still optimized the javascript code a bit though.

**Comment by rxu** [comment]
Works fine for me, thanks.

**Pull request merged**
