### PR TITLE
Add notification to skeleton

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by rxu** [comment]
Looks good.

**Comment by rxu** [comment]
@VSEphpbb It has merge conflicts now.

**Comment by VSEphpbb** [comment]
I know. Trying to work on it from out of town. 😩

**Comment by VSEphpbb** [comment]
OK that should be good now, but it needs testing again.

**Comment by rxu** [comment]
Testing it, got issue with 'not valid YAML' file for services.yml like
> Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 37 (near " arguments:").

I guess there's a problem with indentations for arguments etc. for notification service.
Additionally, arguments are to be wrapped into quotes :smiley:

**Comment by VSEphpbb** [comment]
Updated. Fixed?

**Comment by rxu** [comment]
Yeah, the error is gone. The notification lang is absent still though (like ```NOTIFICATION_TYPE_RXU.NEWEXT.NOTIFICATION.TYPE.DEMO```), other than that, looks ok.

**Comment by VSEphpbb** [comment]
Sweet son of Zeus!!

**Comment by VSEphpbb** [comment]
@rxu How are you seeing that language key? I don't ever see it (because the notification is never actually put to use in it's skeleton form.)

**Comment by VSEphpbb** [comment]
Updated

**Comment by rxu** [comment]
Looks great for me now, thanks.

**Pull request merged**
